2025-01-19 12:48:53,480 - unknown_slug - Error al conectar a la base de datos [Prueba] , Host: [localhost], Port: [1433], Usuario: [sa], Password: [*****]. Error : [(pyodbc.OperationalError) ('08001', '[08001] [Microsoft][ODBC Driver 17 for SQL Server]TCP Provider: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión.\r\n (10061) (SQLDriverConnect); [08001] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0); [08001] [Microsoft][ODBC Driver 17 for SQL Server]Invalid connection string attribute (0); [08001] [Microsoft][ODBC Driver 17 for SQL Server]A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online. (10061)')
(Background on this error at: https://sqlalche.me/e/20/e3q8)]
2025-01-19 12:48:53,608 - unknown_slug - Se ha establecido la conexion con la base de datos local Postgres
2025-01-19 12:48:53,629 - unknown_slug - Modo Desarrollador activado [Para desabilitar el modo desarrollador cambie la variable 'DEBUG' en el archivo .env]
2025-01-19 12:48:53,633 - unknown_slug - Error de conexion con el sistema Odoo: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión
2025-01-19 12:48:53,638 - unknown_slug - Host_Odoo: [http://localhost:8069] - User_Odoo: [useremail@gmail.com] - Password_Odoo: [krlitos] - DB_Odoo: [prueba] 
2025-01-19 12:48:58,335 - unknown_slug - Finalizando el Servicio
2025-01-19 12:50:04,006 - unknown_slug - Error al conectar a la base de datos [Prueba] , Host: [localhost], Port: [1433], Usuario: [sa], Password: [*****]. Error : [(pyodbc.OperationalError) ('08001', '[08001] [Microsoft][ODBC Driver 17 for SQL Server]TCP Provider: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión.\r\n (10061) (SQLDriverConnect); [08001] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0); [08001] [Microsoft][ODBC Driver 17 for SQL Server]Invalid connection string attribute (0); [08001] [Microsoft][ODBC Driver 17 for SQL Server]A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online. (10061)')
(Background on this error at: https://sqlalche.me/e/20/e3q8)]
2025-01-19 12:50:04,132 - unknown_slug - Se ha establecido la conexion con la base de datos local Postgres
2025-01-19 12:50:04,142 - unknown_slug - Modo Desarrollador activado [Para desabilitar el modo desarrollador cambie la variable 'DEBUG' en el archivo .env]
2025-01-19 12:50:04,147 - unknown_slug - Error de conexion con el sistema Odoo: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión
2025-01-19 12:50:04,150 - unknown_slug - Host_Odoo: [http://localhost:8069] - User_Odoo: [useremail@gmail.com] - Password_Odoo: [krlitos] - DB_Odoo: [prueba] 
2025-01-19 12:50:08,414 - 910w3xzcz1sa2ne3u5bv - {"host": "127.0.0.1", "request": "POST http://127.0.0.1:8000/api/v1/synclineal/", "headers": {"host": "127.0.0.1:8000", "connection": "keep-alive", "content-length": "68", "client_name_header": "SyncLineal", "sec-ch-ua-platform": "\"Windows\"", "sec-ch-ua": "\"Google Chrome\";v=\"131\", \"Chromium\";v=\"131\", \"Not_A Brand\";v=\"24\"", "sec-ch-ua-mobile": "?0", "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36", "accept": "application/json", "content-type": "application/json", "id_event_header": "TestSyncLineal", "origin": "http://127.0.0.1:8000", "sec-fetch-site": "same-origin", "sec-fetch-mode": "cors", "sec-fetch-dest": "empty", "referer": "http://127.0.0.1:8000/api/v1/docs", "accept-encoding": "gzip, deflate, br, zstd", "accept-language": "en-US,en;q=0.9,es;q=0.8", "cookie": "_ga=GA1.1.1550307865.1730360116; _ga_TRBNXHQ0ZF=GS1.1.1730386478.2.0.1730386478.0.0.0; csrftoken=9hytPsARZqAgOZ96HGjRVfdJf7jPHBx9"}, "body": "{\n  \"id\": 0,\n  \"tipo_persona_id\": [\n    1,\n    2,\n    3,\n    4\n  ]\n}", "slug": "910w3xzcz1sa2ne3u5bv"}
2025-01-19 12:50:08,418 - unknown_slug - Buscando datos del cliente con ID [0] en la Base de datos de Odoo, en la tabla ['res.partner']
2025-01-19 12:50:08,419 - unknown_slug - Buscando datos del cliente con ID [0] en la Base de datos de Odoo, en la tabla ['res.partner']
2025-01-19 12:50:12,500 - unknown_slug - No se encontro ningun cliente con el id [0] en la tabla [res.partner]. Es probable que este cliente no se encuentre en la base de datos o se encuentre con el campo [active=false]. Error: [cannot marshal None unless allow_none is enabled]
2025-01-19 12:50:12,500 - unknown_slug - No se encontro ningun cliente con el id [0] en la tabla [res.partner]. Es probable que este cliente no se encuentre en la base de datos o se encuentre con el campo [active=false]. Error: [cannot marshal None unless allow_none is enabled]
2025-01-19 12:50:22,527 - unknown_slug - Buscando datos del cliente con ID [0] en la Base de datos de Odoo, en la tabla ['res.partner']
2025-01-19 12:50:26,575 - unknown_slug - No se encontro ningun cliente con el id [0] en la tabla [res.partner]. Es probable que este cliente no se encuentre en la base de datos o se encuentre con el campo [active=false]. Error: [cannot marshal None unless allow_none is enabled]
2025-01-19 12:50:56,748 - 910w3xzcz1sa2ne3u5bv - Finalizando el Servicio
2025-01-19 12:53:57,285 - unknown_slug - Error al conectar a la base de datos [Prueba] , Host: [localhost], Port: [1433], Usuario: [sa], Password: [*****]. Error : [(pyodbc.OperationalError) ('08001', '[08001] [Microsoft][ODBC Driver 17 for SQL Server]TCP Provider: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión.\r\n (10061) (SQLDriverConnect); [08001] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0); [08001] [Microsoft][ODBC Driver 17 for SQL Server]Invalid connection string attribute (0); [08001] [Microsoft][ODBC Driver 17 for SQL Server]A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online. (10061)')
(Background on this error at: https://sqlalche.me/e/20/e3q8)]
2025-01-19 12:53:57,410 - unknown_slug - Se ha establecido la conexion con la base de datos local Postgres
2025-01-19 12:53:57,431 - unknown_slug - Modo Desarrollador activado [Para desabilitar el modo desarrollador cambie la variable 'DEBUG' en el archivo .env]
2025-01-19 12:53:57,436 - unknown_slug - Error de conexion con el sistema Odoo: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión
2025-01-19 12:53:57,439 - unknown_slug - Host_Odoo: [http://localhost:8069] - User_Odoo: [useremail@gmail.com] - Password_Odoo: [krlitos] - DB_Odoo: [prueba] 
2025-01-19 12:54:05,651 - kbl898md1de3q6l159lv - {"host": "127.0.0.1", "request": "POST http://127.0.0.1:8000/api/v1/synclineal/", "headers": {"host": "127.0.0.1:8000", "connection": "keep-alive", "content-length": "68", "client_name_header": "SyncLineal", "sec-ch-ua-platform": "\"Windows\"", "sec-ch-ua": "\"Google Chrome\";v=\"131\", \"Chromium\";v=\"131\", \"Not_A Brand\";v=\"24\"", "sec-ch-ua-mobile": "?0", "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36", "accept": "application/json", "content-type": "application/json", "id_event_header": "TestSyncLineal", "origin": "http://127.0.0.1:8000", "sec-fetch-site": "same-origin", "sec-fetch-mode": "cors", "sec-fetch-dest": "empty", "referer": "http://127.0.0.1:8000/api/v1/docs", "accept-encoding": "gzip, deflate, br, zstd", "accept-language": "en-US,en;q=0.9,es;q=0.8", "cookie": "_ga=GA1.1.1550307865.1730360116; _ga_TRBNXHQ0ZF=GS1.1.1730386478.2.0.1730386478.0.0.0; csrftoken=9hytPsARZqAgOZ96HGjRVfdJf7jPHBx9"}, "body": "{\n  \"id\": 0,\n  \"tipo_persona_id\": [\n    1,\n    2,\n    3,\n    4\n  ]\n}", "slug": "kbl898md1de3q6l159lv"}
2025-01-19 12:54:05,658 - unknown_slug - Buscando datos del cliente con ID [0] en la Base de datos de Odoo, en la tabla ['res.partner']
2025-01-19 12:54:05,659 - unknown_slug - Buscando datos del cliente con ID [0] en la Base de datos de Odoo, en la tabla ['res.partner']
2025-01-19 12:54:09,730 - unknown_slug - No se encontro ningun cliente con el id [0] en la tabla [res.partner]. Es probable que este cliente no se encuentre en la base de datos o se encuentre con el campo [active=false]. Error: [cannot marshal None unless allow_none is enabled]
2025-01-19 12:54:09,730 - unknown_slug - No se encontro ningun cliente con el id [0] en la tabla [res.partner]. Es probable que este cliente no se encuentre en la base de datos o se encuentre con el campo [active=false]. Error: [cannot marshal None unless allow_none is enabled]
2025-01-19 12:54:19,755 - unknown_slug - Buscando datos del cliente con ID [0] en la Base de datos de Odoo, en la tabla ['res.partner']
2025-01-19 12:54:23,779 - unknown_slug - No se encontro ningun cliente con el id [0] en la tabla [res.partner]. Es probable que este cliente no se encuentre en la base de datos o se encuentre con el campo [active=false]. Error: [cannot marshal None unless allow_none is enabled]
2025-01-19 12:55:18,651 - kbl898md1de3q6l159lv - Finalizando el Servicio
2025-01-19 12:55:54,856 - unknown_slug - Error al conectar a la base de datos [Prueba] , Host: [localhost], Port: [1433], Usuario: [sa], Password: [*****]. Error : [(pyodbc.OperationalError) ('08001', '[08001] [Microsoft][ODBC Driver 17 for SQL Server]TCP Provider: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión.\r\n (10061) (SQLDriverConnect); [08001] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0); [08001] [Microsoft][ODBC Driver 17 for SQL Server]Invalid connection string attribute (0); [08001] [Microsoft][ODBC Driver 17 for SQL Server]A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online. (10061)')
(Background on this error at: https://sqlalche.me/e/20/e3q8)]
2025-01-19 12:55:54,984 - unknown_slug - Se ha establecido la conexion con la base de datos local Postgres
2025-01-19 12:55:54,996 - unknown_slug - Modo Desarrollador activado [Para desabilitar el modo desarrollador cambie la variable 'DEBUG' en el archivo .env]
2025-01-19 12:55:54,999 - unknown_slug - Error de conexion con el sistema Odoo: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión
2025-01-19 12:55:55,001 - unknown_slug - Host_Odoo: [http://localhost:8069] - User_Odoo: [useremail@gmail.com] - Password_Odoo: [krlitos] - DB_Odoo: [prueba] 
2025-01-19 12:55:58,623 - 56hrpxp3q3ljojhan194 - {"host": "127.0.0.1", "request": "POST http://127.0.0.1:8000/api/v1/synclineal/", "headers": {"host": "127.0.0.1:8000", "connection": "keep-alive", "content-length": "68", "client_name_header": "SyncLineal", "sec-ch-ua-platform": "\"Windows\"", "sec-ch-ua": "\"Google Chrome\";v=\"131\", \"Chromium\";v=\"131\", \"Not_A Brand\";v=\"24\"", "sec-ch-ua-mobile": "?0", "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36", "accept": "application/json", "content-type": "application/json", "id_event_header": "TestSyncLineal", "origin": "http://127.0.0.1:8000", "sec-fetch-site": "same-origin", "sec-fetch-mode": "cors", "sec-fetch-dest": "empty", "referer": "http://127.0.0.1:8000/api/v1/docs", "accept-encoding": "gzip, deflate, br, zstd", "accept-language": "en-US,en;q=0.9,es;q=0.8", "cookie": "_ga=GA1.1.1550307865.1730360116; _ga_TRBNXHQ0ZF=GS1.1.1730386478.2.0.1730386478.0.0.0; csrftoken=9hytPsARZqAgOZ96HGjRVfdJf7jPHBx9"}, "body": "{\n  \"id\": 0,\n  \"tipo_persona_id\": [\n    1,\n    2,\n    3,\n    4\n  ]\n}", "slug": "56hrpxp3q3ljojhan194"}
2025-01-19 12:55:58,625 - 56hrpxp3q3ljojhan194 - Buscando datos del cliente con ID [0] en la Base de datos de Odoo, en la tabla ['res.partner']
2025-01-19 12:56:02,653 - 56hrpxp3q3ljojhan194 - No se encontro ningun cliente con el id [0] en la tabla [res.partner]. Es probable que este cliente no se encuentre en la base de datos o se encuentre con el campo [active=false]. Error: [cannot marshal None unless allow_none is enabled]
2025-01-19 12:56:02,653 - 56hrpxp3q3ljojhan194 - Buscando datos del cliente con ID [0] en la Base de datos de Odoo, en la tabla ['res.partner']
2025-01-19 12:56:06,711 - 56hrpxp3q3ljojhan194 - No se encontro ningun cliente con el id [0] en la tabla [res.partner]. Es probable que este cliente no se encuentre en la base de datos o se encuentre con el campo [active=false]. Error: [cannot marshal None unless allow_none is enabled]
2025-01-19 12:56:06,711 - 56hrpxp3q3ljojhan194 - Buscando datos del cliente con ID [0] en la Base de datos de Odoo, en la tabla ['res.partner']
2025-01-19 12:56:10,735 - 56hrpxp3q3ljojhan194 - No se encontro ningun cliente con el id [0] en la tabla [res.partner]. Es probable que este cliente no se encuentre en la base de datos o se encuentre con el campo [active=false]. Error: [cannot marshal None unless allow_none is enabled]
2025-01-19 12:56:27,819 - 56hrpxp3q3ljojhan194 - Finalizando el Servicio
2025-01-19 12:57:04,218 - unknown_slug - Error al conectar a la base de datos [Prueba] , Host: [localhost], Port: [1433], Usuario: [sa], Password: [*****]. Error : [(pyodbc.OperationalError) ('08001', '[08001] [Microsoft][ODBC Driver 17 for SQL Server]TCP Provider: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión.\r\n (10061) (SQLDriverConnect); [08001] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0); [08001] [Microsoft][ODBC Driver 17 for SQL Server]Invalid connection string attribute (0); [08001] [Microsoft][ODBC Driver 17 for SQL Server]A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online. (10061)')
(Background on this error at: https://sqlalche.me/e/20/e3q8)]
2025-01-19 12:57:04,349 - unknown_slug - Se ha establecido la conexion con la base de datos local Postgres
2025-01-19 12:57:04,357 - unknown_slug - Modo Desarrollador activado [Para desabilitar el modo desarrollador cambie la variable 'DEBUG' en el archivo .env]
2025-01-19 12:57:04,362 - unknown_slug - Error de conexion con el sistema Odoo: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión
2025-01-19 12:57:04,368 - unknown_slug - Host_Odoo: [http://localhost:8069] - User_Odoo: [useremail@gmail.com] - Password_Odoo: [krlitos] - DB_Odoo: [prueba] 
2025-01-19 12:58:41,793 - 6qpy0ir0s67l9nxhtkgc - {"host": "127.0.0.1", "request": "POST http://127.0.0.1:8000/api/v1/synclineal/", "headers": {"host": "127.0.0.1:8000", "connection": "keep-alive", "content-length": "68", "client_name_header": "SyncLineal", "sec-ch-ua-platform": "\"Windows\"", "sec-ch-ua": "\"Google Chrome\";v=\"131\", \"Chromium\";v=\"131\", \"Not_A Brand\";v=\"24\"", "sec-ch-ua-mobile": "?0", "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36", "accept": "application/json", "content-type": "application/json", "id_event_header": "TestSyncLineal", "origin": "http://127.0.0.1:8000", "sec-fetch-site": "same-origin", "sec-fetch-mode": "cors", "sec-fetch-dest": "empty", "referer": "http://127.0.0.1:8000/api/v1/docs", "accept-encoding": "gzip, deflate, br, zstd", "accept-language": "en-US,en;q=0.9,es;q=0.8", "cookie": "_ga=GA1.1.1550307865.1730360116; _ga_TRBNXHQ0ZF=GS1.1.1730386478.2.0.1730386478.0.0.0; csrftoken=9hytPsARZqAgOZ96HGjRVfdJf7jPHBx9"}, "body": "{\n  \"id\": 0,\n  \"tipo_persona_id\": [\n    1,\n    2,\n    3,\n    4\n  ]\n}", "slug": "6qpy0ir0s67l9nxhtkgc"}
2025-01-19 12:58:41,795 - 6qpy0ir0s67l9nxhtkgc - Buscando datos del cliente con ID [0] en la Base de datos de Odoo, en la tabla ['res.partner']
2025-01-19 12:58:45,839 - 6qpy0ir0s67l9nxhtkgc - No se encontro ningun cliente con el id [0] en la tabla [res.partner]. Es probable que este cliente no se encuentre en la base de datos o se encuentre con el campo [active=false]. Error: [cannot marshal None unless allow_none is enabled]
2025-01-19 12:58:55,849 - 6qpy0ir0s67l9nxhtkgc - Buscando datos del cliente con ID [0] en la Base de datos de Odoo, en la tabla ['res.partner']
2025-01-19 12:58:59,872 - 6qpy0ir0s67l9nxhtkgc - No se encontro ningun cliente con el id [0] en la tabla [res.partner]. Es probable que este cliente no se encuentre en la base de datos o se encuentre con el campo [active=false]. Error: [cannot marshal None unless allow_none is enabled]
2025-01-19 12:59:09,882 - 6qpy0ir0s67l9nxhtkgc - Buscando datos del cliente con ID [0] en la Base de datos de Odoo, en la tabla ['res.partner']
2025-01-19 12:59:13,925 - 6qpy0ir0s67l9nxhtkgc - No se encontro ningun cliente con el id [0] en la tabla [res.partner]. Es probable que este cliente no se encuentre en la base de datos o se encuentre con el campo [active=false]. Error: [cannot marshal None unless allow_none is enabled]
2025-01-19 13:03:02,483 - 6qpy0ir0s67l9nxhtkgc - Finalizando el Servicio
2025-01-19 13:15:14,094 - unknown_slug - Error al conectar a la base de datos [Prueba] , Host: [localhost], Port: [1433], Usuario: [sa], Password: [*****]. Error : [(pyodbc.OperationalError) ('08001', '[08001] [Microsoft][ODBC Driver 17 for SQL Server]TCP Provider: Tiempo de espera de la operación de espera agotado.\r\n (258) (SQLDriverConnect); [08001] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0); [08001] [Microsoft][ODBC Driver 17 for SQL Server]Invalid connection string attribute (0); [08001] [Microsoft][ODBC Driver 17 for SQL Server]A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online. (258)')
(Background on this error at: https://sqlalche.me/e/20/e3q8)]
2025-01-19 13:15:14,348 - unknown_slug - Se ha establecido la conexion con la base de datos local Postgres
2025-01-19 13:15:14,363 - unknown_slug - Modo Desarrollador activado [Para desabilitar el modo desarrollador cambie la variable 'DEBUG' en el archivo .env]
2025-01-19 13:15:14,372 - unknown_slug - Error de conexion con el sistema Odoo: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión
2025-01-19 13:15:14,377 - unknown_slug - Host_Odoo: [http://localhost:8069] - User_Odoo: [useremail@gmail.com] - Password_Odoo: [krlitos] - DB_Odoo: [prueba] 
2025-01-19 13:15:16,439 - unknown_slug - Finalizando el Servicio
2025-01-19 13:15:38,799 - unknown_slug - Error al conectar a la base de datos [Prueba] , Host: [localhost], Port: [1433], Usuario: [sa], Password: [*****]. Error : [(pyodbc.OperationalError) ('08001', '[08001] [Microsoft][ODBC Driver 17 for SQL Server]TCP Provider: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión.\r\n (10061) (SQLDriverConnect); [08001] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0); [08001] [Microsoft][ODBC Driver 17 for SQL Server]Invalid connection string attribute (0); [08001] [Microsoft][ODBC Driver 17 for SQL Server]A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online. (10061)')
(Background on this error at: https://sqlalche.me/e/20/e3q8)]
2025-01-19 13:15:38,935 - unknown_slug - Se ha establecido la conexion con la base de datos local Postgres
2025-01-19 13:15:38,944 - unknown_slug - Modo Desarrollador activado [Para desabilitar el modo desarrollador cambie la variable 'DEBUG' en el archivo .env]
2025-01-19 13:15:38,948 - unknown_slug - Error de conexion con el sistema Odoo: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión
2025-01-19 13:15:38,957 - unknown_slug - Host_Odoo: [http://localhost:8069] - User_Odoo: [useremail@gmail.com] - Password_Odoo: [krlitos] - DB_Odoo: [prueba] 
2025-01-19 13:15:46,048 - dzn7r699nhm9nvn7rof3 - {"host": "127.0.0.1", "request": "POST http://127.0.0.1:8000/api/v1/synclineal/", "headers": {"host": "127.0.0.1:8000", "connection": "keep-alive", "content-length": "68", "client_name_header": "SyncLineal", "sec-ch-ua-platform": "\"Windows\"", "sec-ch-ua": "\"Google Chrome\";v=\"131\", \"Chromium\";v=\"131\", \"Not_A Brand\";v=\"24\"", "sec-ch-ua-mobile": "?0", "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36", "accept": "application/json", "content-type": "application/json", "id_event_header": "TestSyncLineal", "origin": "http://127.0.0.1:8000", "sec-fetch-site": "same-origin", "sec-fetch-mode": "cors", "sec-fetch-dest": "empty", "referer": "http://127.0.0.1:8000/api/v1/docs", "accept-encoding": "gzip, deflate, br, zstd", "accept-language": "en-US,en;q=0.9,es;q=0.8", "cookie": "_ga=GA1.1.1550307865.1730360116; _ga_TRBNXHQ0ZF=GS1.1.1730386478.2.0.1730386478.0.0.0; csrftoken=9hytPsARZqAgOZ96HGjRVfdJf7jPHBx9"}, "body": "{\n  \"id\": 0,\n  \"tipo_persona_id\": [\n    1,\n    2,\n    3,\n    4\n  ]\n}", "slug": "dzn7r699nhm9nvn7rof3"}
2025-01-19 13:15:46,049 - unknown_slug - Buscando datos del cliente con ID [0] en la Base de datos de Odoo, en la tabla ['res.partner']
2025-01-19 13:15:46,053 - unknown_slug - Buscando datos del cliente con ID [0] en la Base de datos de Odoo, en la tabla ['res.partner']
2025-01-19 13:15:46,053 - unknown_slug - Buscando datos del cliente con ID [0] en la Base de datos de Odoo, en la tabla ['res.partner']
2025-01-19 13:15:50,113 - unknown_slug - No se encontro ningun cliente con el id [0] en la tabla [res.partner]. Es probable que este cliente no se encuentre en la base de datos o se encuentre con el campo [active=false]. Error: [cannot marshal None unless allow_none is enabled]
2025-01-19 13:15:50,113 - unknown_slug - No se encontro ningun cliente con el id [0] en la tabla [res.partner]. Es probable que este cliente no se encuentre en la base de datos o se encuentre con el campo [active=false]. Error: [cannot marshal None unless allow_none is enabled]
2025-01-19 13:15:50,113 - unknown_slug - No se encontro ningun cliente con el id [0] en la tabla [res.partner]. Es probable que este cliente no se encuentre en la base de datos o se encuentre con el campo [active=false]. Error: [cannot marshal None unless allow_none is enabled]
2025-01-19 13:18:57,033 - dzn7r699nhm9nvn7rof3 - Finalizando el Servicio
2025-01-19 13:19:19,351 - unknown_slug - Error al conectar a la base de datos [Prueba] , Host: [localhost], Port: [1433], Usuario: [sa], Password: [*****]. Error : [(pyodbc.OperationalError) ('08001', '[08001] [Microsoft][ODBC Driver 17 for SQL Server]TCP Provider: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión.\r\n (10061) (SQLDriverConnect); [08001] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0); [08001] [Microsoft][ODBC Driver 17 for SQL Server]Invalid connection string attribute (0); [08001] [Microsoft][ODBC Driver 17 for SQL Server]A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online. (10061)')
(Background on this error at: https://sqlalche.me/e/20/e3q8)]
2025-01-19 13:19:19,480 - unknown_slug - Se ha establecido la conexion con la base de datos local Postgres
2025-01-19 13:19:19,495 - unknown_slug - Modo Desarrollador activado [Para desabilitar el modo desarrollador cambie la variable 'DEBUG' en el archivo .env]
2025-01-19 13:19:19,500 - unknown_slug - Error de conexion con el sistema Odoo: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión
2025-01-19 13:19:19,505 - unknown_slug - Host_Odoo: [http://localhost:8069] - User_Odoo: [useremail@gmail.com] - Password_Odoo: [krlitos] - DB_Odoo: [prueba] 
2025-01-19 13:19:27,798 - uygg6mduuib49xgp0o7u - {"host": "127.0.0.1", "request": "POST http://127.0.0.1:8000/api/v1/synclineal/", "headers": {"host": "127.0.0.1:8000", "connection": "keep-alive", "content-length": "68", "client_name_header": "SyncLineal", "sec-ch-ua-platform": "\"Windows\"", "sec-ch-ua": "\"Google Chrome\";v=\"131\", \"Chromium\";v=\"131\", \"Not_A Brand\";v=\"24\"", "sec-ch-ua-mobile": "?0", "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36", "accept": "application/json", "content-type": "application/json", "id_event_header": "TestSyncLineal", "origin": "http://127.0.0.1:8000", "sec-fetch-site": "same-origin", "sec-fetch-mode": "cors", "sec-fetch-dest": "empty", "referer": "http://127.0.0.1:8000/api/v1/docs", "accept-encoding": "gzip, deflate, br, zstd", "accept-language": "en-US,en;q=0.9,es;q=0.8", "cookie": "_ga=GA1.1.1550307865.1730360116; _ga_TRBNXHQ0ZF=GS1.1.1730386478.2.0.1730386478.0.0.0; csrftoken=9hytPsARZqAgOZ96HGjRVfdJf7jPHBx9"}, "body": "{\n  \"id\": 0,\n  \"tipo_persona_id\": [\n    1,\n    2,\n    3,\n    4\n  ]\n}", "slug": "uygg6mduuib49xgp0o7u"}
2025-01-19 13:19:27,802 - unknown_slug - Buscando datos del cliente con ID [0] en la Base de datos de Odoo, en la tabla ['res.partner']
2025-01-19 13:19:27,805 - unknown_slug - Buscando datos del cliente con ID [0] en la Base de datos de Odoo, en la tabla ['res.partner']
2025-01-19 13:19:27,806 - unknown_slug - Buscando datos del cliente con ID [0] en la Base de datos de Odoo, en la tabla ['res.partner']
2025-01-19 13:19:31,858 - unknown_slug - No se encontro ningun cliente con el id [0] en la tabla [res.partner]. Es probable que este cliente no se encuentre en la base de datos o se encuentre con el campo [active=false]. Error: [cannot marshal None unless allow_none is enabled]
2025-01-19 13:19:31,858 - unknown_slug - No se encontro ningun cliente con el id [0] en la tabla [res.partner]. Es probable que este cliente no se encuentre en la base de datos o se encuentre con el campo [active=false]. Error: [cannot marshal None unless allow_none is enabled]
2025-01-19 13:19:31,858 - unknown_slug - No se encontro ningun cliente con el id [0] en la tabla [res.partner]. Es probable que este cliente no se encuentre en la base de datos o se encuentre con el campo [active=false]. Error: [cannot marshal None unless allow_none is enabled]
2025-01-19 13:22:21,252 - uygg6mduuib49xgp0o7u - Finalizando el Servicio
2025-01-19 13:22:45,572 - unknown_slug - Error al conectar a la base de datos [Prueba] , Host: [localhost], Port: [1433], Usuario: [sa], Password: [*****]. Error : [(pyodbc.OperationalError) ('08001', '[08001] [Microsoft][ODBC Driver 17 for SQL Server]TCP Provider: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión.\r\n (10061) (SQLDriverConnect); [08001] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0); [08001] [Microsoft][ODBC Driver 17 for SQL Server]Invalid connection string attribute (0); [08001] [Microsoft][ODBC Driver 17 for SQL Server]A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online. (10061)')
(Background on this error at: https://sqlalche.me/e/20/e3q8)]
2025-01-19 13:22:45,711 - unknown_slug - Se ha establecido la conexion con la base de datos local Postgres
2025-01-19 13:22:45,724 - unknown_slug - Modo Desarrollador activado [Para desabilitar el modo desarrollador cambie la variable 'DEBUG' en el archivo .env]
2025-01-19 13:22:45,732 - unknown_slug - Error de conexion con el sistema Odoo: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión
2025-01-19 13:22:45,736 - unknown_slug - Host_Odoo: [http://localhost:8069] - User_Odoo: [useremail@gmail.com] - Password_Odoo: [krlitos] - DB_Odoo: [prueba] 
2025-01-19 13:22:52,296 - zxhyxzua6nxgj1m9fk8j - {"host": "127.0.0.1", "request": "POST http://127.0.0.1:8000/api/v1/synclineal/", "headers": {"host": "127.0.0.1:8000", "connection": "keep-alive", "content-length": "68", "client_name_header": "SyncLineal", "sec-ch-ua-platform": "\"Windows\"", "sec-ch-ua": "\"Google Chrome\";v=\"131\", \"Chromium\";v=\"131\", \"Not_A Brand\";v=\"24\"", "sec-ch-ua-mobile": "?0", "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36", "accept": "application/json", "content-type": "application/json", "id_event_header": "TestSyncLineal", "origin": "http://127.0.0.1:8000", "sec-fetch-site": "same-origin", "sec-fetch-mode": "cors", "sec-fetch-dest": "empty", "referer": "http://127.0.0.1:8000/api/v1/docs", "accept-encoding": "gzip, deflate, br, zstd", "accept-language": "en-US,en;q=0.9,es;q=0.8", "cookie": "_ga=GA1.1.1550307865.1730360116; _ga_TRBNXHQ0ZF=GS1.1.1730386478.2.0.1730386478.0.0.0; csrftoken=9hytPsARZqAgOZ96HGjRVfdJf7jPHBx9"}, "body": "{\n  \"id\": 0,\n  \"tipo_persona_id\": [\n    1,\n    2,\n    3,\n    4\n  ]\n}", "slug": "zxhyxzua6nxgj1m9fk8j"}
2025-01-19 13:22:52,303 - unknown_slug - Buscando datos del cliente con ID [0] en la Base de datos de Odoo, en la tabla ['res.partner']
2025-01-19 13:22:52,303 - unknown_slug - Buscando datos del cliente con ID [0] en la Base de datos de Odoo, en la tabla ['res.partner']
2025-01-19 13:22:52,303 - unknown_slug - Buscando datos del cliente con ID [0] en la Base de datos de Odoo, en la tabla ['res.partner']
2025-01-19 13:22:56,330 - unknown_slug - No se encontro ningun cliente con el id [0] en la tabla [res.partner]. Es probable que este cliente no se encuentre en la base de datos o se encuentre con el campo [active=false]. Error: [cannot marshal None unless allow_none is enabled]
2025-01-19 13:22:56,330 - unknown_slug - No se encontro ningun cliente con el id [0] en la tabla [res.partner]. Es probable que este cliente no se encuentre en la base de datos o se encuentre con el campo [active=false]. Error: [cannot marshal None unless allow_none is enabled]
2025-01-19 13:22:56,346 - unknown_slug - No se encontro ningun cliente con el id [0] en la tabla [res.partner]. Es probable que este cliente no se encuentre en la base de datos o se encuentre con el campo [active=false]. Error: [cannot marshal None unless allow_none is enabled]
2025-01-19 13:25:13,470 - unknown_slug - Error al conectar a la base de datos [Prueba] , Host: [localhost], Port: [1433], Usuario: [sa], Password: [*****]. Error : [(pyodbc.OperationalError) ('08001', '[08001] [Microsoft][ODBC Driver 17 for SQL Server]TCP Provider: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión.\r\n (10061) (SQLDriverConnect); [08001] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0); [08001] [Microsoft][ODBC Driver 17 for SQL Server]Invalid connection string attribute (0); [08001] [Microsoft][ODBC Driver 17 for SQL Server]A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online. (10061)')
(Background on this error at: https://sqlalche.me/e/20/e3q8)]
2025-01-19 13:25:13,606 - unknown_slug - Se ha establecido la conexion con la base de datos local Postgres
2025-01-19 13:25:13,617 - unknown_slug - Modo Desarrollador activado [Para desabilitar el modo desarrollador cambie la variable 'DEBUG' en el archivo .env]
2025-01-19 13:25:13,620 - unknown_slug - Error de conexion con el sistema Odoo: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión
2025-01-19 13:25:13,626 - unknown_slug - Host_Odoo: [http://localhost:8069] - User_Odoo: [useremail@gmail.com] - Password_Odoo: [krlitos] - DB_Odoo: [prueba] 
2025-01-19 13:25:23,174 - nhv0limyrcrt33sfg02r - {"host": "127.0.0.1", "request": "POST http://127.0.0.1:8000/api/v1/synclineal/", "headers": {"host": "127.0.0.1:8000", "connection": "keep-alive", "content-length": "68", "client_name_header": "SyncLineal", "sec-ch-ua-platform": "\"Windows\"", "sec-ch-ua": "\"Google Chrome\";v=\"131\", \"Chromium\";v=\"131\", \"Not_A Brand\";v=\"24\"", "sec-ch-ua-mobile": "?0", "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36", "accept": "application/json", "content-type": "application/json", "id_event_header": "TestSyncLineal", "origin": "http://127.0.0.1:8000", "sec-fetch-site": "same-origin", "sec-fetch-mode": "cors", "sec-fetch-dest": "empty", "referer": "http://127.0.0.1:8000/api/v1/docs", "accept-encoding": "gzip, deflate, br, zstd", "accept-language": "en-US,en;q=0.9,es;q=0.8", "cookie": "_ga=GA1.1.1550307865.1730360116; _ga_TRBNXHQ0ZF=GS1.1.1730386478.2.0.1730386478.0.0.0; csrftoken=9hytPsARZqAgOZ96HGjRVfdJf7jPHBx9"}, "body": "{\n  \"id\": 0,\n  \"tipo_persona_id\": [\n    1,\n    2,\n    3,\n    4\n  ]\n}", "slug": "nhv0limyrcrt33sfg02r"}
2025-01-19 13:25:23,180 - unknown_slug - Buscando datos del cliente con ID [0] en la Base de datos de Odoo, en la tabla ['res.partner']
2025-01-19 13:25:23,182 - unknown_slug - Buscando datos del cliente con ID [0] en la Base de datos de Odoo, en la tabla ['res.partner']
2025-01-19 13:25:23,183 - unknown_slug - Buscando datos del cliente con ID [0] en la Base de datos de Odoo, en la tabla ['res.partner']
2025-01-19 13:25:27,222 - unknown_slug - No se encontro ningun cliente con el id [0] en la tabla [res.partner]. Es probable que este cliente no se encuentre en la base de datos o se encuentre con el campo [active=false]. Error: [cannot marshal None unless allow_none is enabled]
2025-01-19 13:25:27,243 - unknown_slug - No se encontro ningun cliente con el id [0] en la tabla [res.partner]. Es probable que este cliente no se encuentre en la base de datos o se encuentre con el campo [active=false]. Error: [cannot marshal None unless allow_none is enabled]
2025-01-19 13:25:27,258 - unknown_slug - No se encontro ningun cliente con el id [0] en la tabla [res.partner]. Es probable que este cliente no se encuentre en la base de datos o se encuentre con el campo [active=false]. Error: [cannot marshal None unless allow_none is enabled]
2025-01-19 13:27:27,850 - nhv0limyrcrt33sfg02r - Finalizando el Servicio
2025-01-19 13:27:54,144 - unknown_slug - Error al conectar a la base de datos [Prueba] , Host: [localhost], Port: [1433], Usuario: [sa], Password: [*****]. Error : [(pyodbc.OperationalError) ('08001', '[08001] [Microsoft][ODBC Driver 17 for SQL Server]TCP Provider: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión.\r\n (10061) (SQLDriverConnect); [08001] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0); [08001] [Microsoft][ODBC Driver 17 for SQL Server]Invalid connection string attribute (0); [08001] [Microsoft][ODBC Driver 17 for SQL Server]A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online. (10061)')
(Background on this error at: https://sqlalche.me/e/20/e3q8)]
2025-01-19 13:27:54,274 - unknown_slug - Se ha establecido la conexion con la base de datos local Postgres
2025-01-19 13:27:54,291 - unknown_slug - Modo Desarrollador activado [Para desabilitar el modo desarrollador cambie la variable 'DEBUG' en el archivo .env]
2025-01-19 13:27:54,297 - unknown_slug - Error de conexion con el sistema Odoo: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión
2025-01-19 13:27:54,301 - unknown_slug - Host_Odoo: [http://localhost:8069] - User_Odoo: [useremail@gmail.com] - Password_Odoo: [krlitos] - DB_Odoo: [prueba] 
2025-01-19 13:28:00,303 - h8e5d47xqr9bm8m3q6p8 - {"host": "127.0.0.1", "request": "POST http://127.0.0.1:8000/api/v1/synclineal/", "headers": {"host": "127.0.0.1:8000", "connection": "keep-alive", "content-length": "68", "client_name_header": "SyncLineal", "sec-ch-ua-platform": "\"Windows\"", "sec-ch-ua": "\"Google Chrome\";v=\"131\", \"Chromium\";v=\"131\", \"Not_A Brand\";v=\"24\"", "sec-ch-ua-mobile": "?0", "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36", "accept": "application/json", "content-type": "application/json", "id_event_header": "TestSyncLineal", "origin": "http://127.0.0.1:8000", "sec-fetch-site": "same-origin", "sec-fetch-mode": "cors", "sec-fetch-dest": "empty", "referer": "http://127.0.0.1:8000/api/v1/docs", "accept-encoding": "gzip, deflate, br, zstd", "accept-language": "en-US,en;q=0.9,es;q=0.8", "cookie": "_ga=GA1.1.1550307865.1730360116; _ga_TRBNXHQ0ZF=GS1.1.1730386478.2.0.1730386478.0.0.0; csrftoken=9hytPsARZqAgOZ96HGjRVfdJf7jPHBx9"}, "body": "{\n  \"id\": 0,\n  \"tipo_persona_id\": [\n    1,\n    2,\n    3,\n    4\n  ]\n}", "slug": "h8e5d47xqr9bm8m3q6p8"}
2025-01-19 13:28:00,305 - h8e5d47xqr9bm8m3q6p8 - Buscando datos del cliente con ID [0] en la Base de datos de Odoo, en la tabla ['res.partner']
2025-01-19 13:28:04,363 - h8e5d47xqr9bm8m3q6p8 - No se encontro ningun cliente con el id [0] en la tabla [res.partner]. Es probable que este cliente no se encuentre en la base de datos o se encuentre con el campo [active=false]. Error: [cannot marshal None unless allow_none is enabled]
2025-01-19 13:28:14,368 - h8e5d47xqr9bm8m3q6p8 - Buscando datos del cliente con ID [0] en la Base de datos de Odoo, en la tabla ['res.partner']
2025-01-19 13:28:18,439 - h8e5d47xqr9bm8m3q6p8 - No se encontro ningun cliente con el id [0] en la tabla [res.partner]. Es probable que este cliente no se encuentre en la base de datos o se encuentre con el campo [active=false]. Error: [cannot marshal None unless allow_none is enabled]
2025-01-19 13:28:28,449 - h8e5d47xqr9bm8m3q6p8 - Buscando datos del cliente con ID [0] en la Base de datos de Odoo, en la tabla ['res.partner']
2025-01-19 13:28:32,490 - h8e5d47xqr9bm8m3q6p8 - No se encontro ningun cliente con el id [0] en la tabla [res.partner]. Es probable que este cliente no se encuentre en la base de datos o se encuentre con el campo [active=false]. Error: [cannot marshal None unless allow_none is enabled]
2025-01-19 13:31:15,710 - h8e5d47xqr9bm8m3q6p8 - Finalizando el Servicio
2025-01-19 13:31:38,145 - unknown_slug - Error al conectar a la base de datos [Prueba] , Host: [localhost], Port: [1433], Usuario: [sa], Password: [*****]. Error : [(pyodbc.OperationalError) ('08001', '[08001] [Microsoft][ODBC Driver 17 for SQL Server]TCP Provider: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión.\r\n (10061) (SQLDriverConnect); [08001] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0); [08001] [Microsoft][ODBC Driver 17 for SQL Server]Invalid connection string attribute (0); [08001] [Microsoft][ODBC Driver 17 for SQL Server]A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online. (10061)')
(Background on this error at: https://sqlalche.me/e/20/e3q8)]
2025-01-19 13:31:38,283 - unknown_slug - Se ha establecido la conexion con la base de datos local Postgres
2025-01-19 13:31:38,294 - unknown_slug - Modo Desarrollador activado [Para desabilitar el modo desarrollador cambie la variable 'DEBUG' en el archivo .env]
2025-01-19 13:31:38,297 - unknown_slug - Error de conexion con el sistema Odoo: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión
2025-01-19 13:31:38,302 - unknown_slug - Host_Odoo: [http://localhost:8069] - User_Odoo: [useremail@gmail.com] - Password_Odoo: [krlitos] - DB_Odoo: [prueba] 
2025-01-19 13:31:48,986 - l8rx0ezr63zz19ydnetn - {"host": "127.0.0.1", "request": "POST http://127.0.0.1:8000/api/v1/synclineal/", "headers": {"host": "127.0.0.1:8000", "connection": "keep-alive", "content-length": "68", "client_name_header": "SyncLineal", "sec-ch-ua-platform": "\"Windows\"", "sec-ch-ua": "\"Google Chrome\";v=\"131\", \"Chromium\";v=\"131\", \"Not_A Brand\";v=\"24\"", "sec-ch-ua-mobile": "?0", "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36", "accept": "application/json", "content-type": "application/json", "id_event_header": "TestSyncLineal", "origin": "http://127.0.0.1:8000", "sec-fetch-site": "same-origin", "sec-fetch-mode": "cors", "sec-fetch-dest": "empty", "referer": "http://127.0.0.1:8000/api/v1/docs", "accept-encoding": "gzip, deflate, br, zstd", "accept-language": "en-US,en;q=0.9,es;q=0.8", "cookie": "_ga=GA1.1.1550307865.1730360116; _ga_TRBNXHQ0ZF=GS1.1.1730386478.2.0.1730386478.0.0.0; csrftoken=9hytPsARZqAgOZ96HGjRVfdJf7jPHBx9"}, "body": "{\n  \"id\": 0,\n  \"tipo_persona_id\": [\n    1,\n    2,\n    3,\n    4\n  ]\n}", "slug": "l8rx0ezr63zz19ydnetn"}
2025-01-19 13:31:49,002 - unknown_slug - Buscando datos del cliente con ID [0] en la Base de datos de Odoo, en la tabla ['res.partner']
2025-01-19 13:31:49,004 - unknown_slug - Buscando datos del cliente con ID [0] en la Base de datos de Odoo, en la tabla ['res.partner']
2025-01-19 13:31:49,004 - unknown_slug - Buscando datos del cliente con ID [0] en la Base de datos de Odoo, en la tabla ['res.partner']
2025-01-19 13:31:53,095 - unknown_slug - No se encontro ningun cliente con el id [0] en la tabla [res.partner]. Es probable que este cliente no se encuentre en la base de datos o se encuentre con el campo [active=false]. Error: [cannot marshal None unless allow_none is enabled]
2025-01-19 13:31:53,095 - unknown_slug - No se encontro ningun cliente con el id [0] en la tabla [res.partner]. Es probable que este cliente no se encuentre en la base de datos o se encuentre con el campo [active=false]. Error: [cannot marshal None unless allow_none is enabled]
2025-01-19 13:31:53,095 - unknown_slug - No se encontro ningun cliente con el id [0] en la tabla [res.partner]. Es probable que este cliente no se encuentre en la base de datos o se encuentre con el campo [active=false]. Error: [cannot marshal None unless allow_none is enabled]
2025-01-19 13:33:37,727 - l8rx0ezr63zz19ydnetn - Finalizando el Servicio
2025-01-19 13:37:49,865 - unknown_slug - Error al conectar a la base de datos [Prueba] , Host: [localhost], Port: [1433], Usuario: [sa], Password: [*****]. Error : [(pyodbc.OperationalError) ('08001', '[08001] [Microsoft][ODBC Driver 17 for SQL Server]TCP Provider: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión.\r\n (10061) (SQLDriverConnect); [08001] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0); [08001] [Microsoft][ODBC Driver 17 for SQL Server]Invalid connection string attribute (0); [08001] [Microsoft][ODBC Driver 17 for SQL Server]A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online. (10061)')
(Background on this error at: https://sqlalche.me/e/20/e3q8)]
2025-01-19 13:39:32,652 - unknown_slug - Error al conectar a la base de datos [Prueba] , Host: [localhost], Port: [1433], Usuario: [sa], Password: [*****]. Error : [(pyodbc.OperationalError) ('08001', '[08001] [Microsoft][ODBC Driver 17 for SQL Server]TCP Provider: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión.\r\n (10061) (SQLDriverConnect); [08001] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0); [08001] [Microsoft][ODBC Driver 17 for SQL Server]Invalid connection string attribute (0); [08001] [Microsoft][ODBC Driver 17 for SQL Server]A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online. (10061)')
(Background on this error at: https://sqlalche.me/e/20/e3q8)]
2025-01-19 13:40:18,209 - unknown_slug - Error al conectar a la base de datos [Prueba] , Host: [localhost], Port: [1433], Usuario: [sa], Password: [*****]. Error : [(pyodbc.OperationalError) ('08001', '[08001] [Microsoft][ODBC Driver 17 for SQL Server]TCP Provider: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión.\r\n (10061) (SQLDriverConnect); [08001] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0); [08001] [Microsoft][ODBC Driver 17 for SQL Server]Invalid connection string attribute (0); [08001] [Microsoft][ODBC Driver 17 for SQL Server]A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online. (10061)')
(Background on this error at: https://sqlalche.me/e/20/e3q8)]
2025-01-19 13:47:59,040 - unknown_slug - Error al conectar a la base de datos [Prueba] , Host: [localhost], Port: [1433], Usuario: [sa], Password: [*****]. Error : [(pyodbc.OperationalError) ('08001', '[08001] [Microsoft][ODBC Driver 17 for SQL Server]TCP Provider: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión.\r\n (10061) (SQLDriverConnect); [08001] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0); [08001] [Microsoft][ODBC Driver 17 for SQL Server]Invalid connection string attribute (0); [08001] [Microsoft][ODBC Driver 17 for SQL Server]A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online. (10061)')
(Background on this error at: https://sqlalche.me/e/20/e3q8)]
2025-01-19 13:47:59,190 - unknown_slug - Se ha establecido la conexion con la base de datos local Postgres
2025-01-19 13:47:59,202 - unknown_slug - Modo Desarrollador activado [Para desabilitar el modo desarrollador cambie la variable 'DEBUG' en el archivo .env]
2025-01-19 13:47:59,206 - unknown_slug - Error de conexion con el sistema Odoo: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión
2025-01-19 13:47:59,211 - unknown_slug - Host_Odoo: [http://localhost:8069] - User_Odoo: [useremail@gmail.com] - Password_Odoo: [krlitos] - DB_Odoo: [prueba] 
2025-01-19 13:48:03,019 - unknown_slug - Finalizando el Servicio
2025-01-19 13:48:36,425 - unknown_slug - Error al conectar a la base de datos [Prueba] , Host: [localhost], Port: [1433], Usuario: [sa], Password: [*****]. Error : [(pyodbc.OperationalError) ('08001', '[08001] [Microsoft][ODBC Driver 17 for SQL Server]TCP Provider: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión.\r\n (10061) (SQLDriverConnect); [08001] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0); [08001] [Microsoft][ODBC Driver 17 for SQL Server]Invalid connection string attribute (0); [08001] [Microsoft][ODBC Driver 17 for SQL Server]A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online. (10061)')
(Background on this error at: https://sqlalche.me/e/20/e3q8)]
2025-01-19 13:48:36,548 - unknown_slug - Se ha establecido la conexion con la base de datos local Postgres
2025-01-19 13:48:36,566 - unknown_slug - Modo Desarrollador activado [Para desabilitar el modo desarrollador cambie la variable 'DEBUG' en el archivo .env]
2025-01-19 13:48:45,751 - unknown_slug - Finalizando el Servicio
2025-01-19 13:48:54,128 - unknown_slug - Se ha establecido la conexion con la base de datos local Postgres
2025-01-19 13:48:54,152 - unknown_slug - Modo Desarrollador activado [Para desabilitar el modo desarrollador cambie la variable 'DEBUG' en el archivo .env]
2025-01-19 13:49:22,943 - unknown_slug - Finalizando el Servicio
2025-01-19 13:49:51,555 - unknown_slug - Error al conectar a la base de datos [Prueba] , Host: [localhost], Port: [1433], Usuario: [sa], Password: [*****]. Error : [(pyodbc.OperationalError) ('08001', '[08001] [Microsoft][ODBC Driver 17 for SQL Server]TCP Provider: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión.\r\n (10061) (SQLDriverConnect); [08001] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0); [08001] [Microsoft][ODBC Driver 17 for SQL Server]Invalid connection string attribute (0); [08001] [Microsoft][ODBC Driver 17 for SQL Server]A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online. (10061)')
(Background on this error at: https://sqlalche.me/e/20/e3q8)]
2025-01-19 13:49:51,697 - unknown_slug - Se ha establecido la conexion con la base de datos local Postgres
2025-01-19 13:49:51,705 - unknown_slug - Modo Desarrollador activado [Para desabilitar el modo desarrollador cambie la variable 'DEBUG' en el archivo .env]
2025-01-19 13:49:51,708 - unknown_slug - Error de conexion con el sistema Odoo: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión
2025-01-19 13:49:51,711 - unknown_slug - Host_Odoo: [http://localhost:8069] - User_Odoo: [useremail@gmail.com] - Password_Odoo: [krlitos] - DB_Odoo: [prueba] 
2025-01-19 13:49:57,149 - owzugsv1iv5w7wgaigvu - {"host": "127.0.0.1", "request": "POST http://127.0.0.1:8000/api/v1/synclineal/", "headers": {"host": "127.0.0.1:8000", "connection": "keep-alive", "content-length": "68", "client_name_header": "SyncLineal", "sec-ch-ua-platform": "\"Windows\"", "sec-ch-ua": "\"Google Chrome\";v=\"131\", \"Chromium\";v=\"131\", \"Not_A Brand\";v=\"24\"", "sec-ch-ua-mobile": "?0", "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36", "accept": "application/json", "content-type": "application/json", "id_event_header": "TestSyncLineal", "origin": "http://127.0.0.1:8000", "sec-fetch-site": "same-origin", "sec-fetch-mode": "cors", "sec-fetch-dest": "empty", "referer": "http://127.0.0.1:8000/api/v1/docs", "accept-encoding": "gzip, deflate, br, zstd", "accept-language": "en-US,en;q=0.9,es;q=0.8", "cookie": "_ga=GA1.1.1550307865.1730360116; _ga_TRBNXHQ0ZF=GS1.1.1730386478.2.0.1730386478.0.0.0; csrftoken=9hytPsARZqAgOZ96HGjRVfdJf7jPHBx9"}, "body": "{\n  \"id\": 0,\n  \"tipo_persona_id\": [\n    1,\n    2,\n    3,\n    4\n  ]\n}", "slug": "owzugsv1iv5w7wgaigvu"}
2025-01-19 13:49:57,153 - unknown_slug - Buscando datos del cliente con ID [0] en la Base de datos de Odoo, en la tabla ['res.partner']
2025-01-19 13:49:57,154 - unknown_slug - Buscando datos del cliente con ID [0] en la Base de datos de Odoo, en la tabla ['res.partner']
2025-01-19 13:49:57,157 - unknown_slug - Buscando datos del cliente con ID [0] en la Base de datos de Odoo, en la tabla ['res.partner']
2025-01-19 13:50:01,212 - unknown_slug - No se encontro ningun cliente con el id [0] en la tabla [res.partner]. Es probable que este cliente no se encuentre en la base de datos o se encuentre con el campo [active=false]. Error: [cannot marshal None unless allow_none is enabled]
2025-01-19 13:50:01,212 - unknown_slug - No se encontro ningun cliente con el id [0] en la tabla [res.partner]. Es probable que este cliente no se encuentre en la base de datos o se encuentre con el campo [active=false]. Error: [cannot marshal None unless allow_none is enabled]
2025-01-19 13:50:01,212 - unknown_slug - No se encontro ningun cliente con el id [0] en la tabla [res.partner]. Es probable que este cliente no se encuentre en la base de datos o se encuentre con el campo [active=false]. Error: [cannot marshal None unless allow_none is enabled]
2025-01-19 13:50:28,835 - owzugsv1iv5w7wgaigvu - Finalizando el Servicio
2025-01-19 13:54:56,384 - unknown_slug - Error al conectar a la base de datos [Prueba] , Host: [localhost], Port: [1433], Usuario: [sa], Password: [*****]. Error : [(pyodbc.OperationalError) ('08001', '[08001] [Microsoft][ODBC Driver 17 for SQL Server]TCP Provider: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión.\r\n (10061) (SQLDriverConnect); [08001] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0); [08001] [Microsoft][ODBC Driver 17 for SQL Server]Invalid connection string attribute (0); [08001] [Microsoft][ODBC Driver 17 for SQL Server]A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online. (10061)')
(Background on this error at: https://sqlalche.me/e/20/e3q8)]
2025-01-19 13:54:56,544 - unknown_slug - Se ha establecido la conexion con la base de datos local Postgres
2025-01-19 13:54:56,555 - unknown_slug - Modo Desarrollador activado [Para desabilitar el modo desarrollador cambie la variable 'DEBUG' en el archivo .env]
2025-01-19 13:54:56,557 - unknown_slug - Error de conexion con el sistema Odoo: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión
2025-01-19 13:54:56,560 - unknown_slug - Host_Odoo: [http://localhost:8069] - User_Odoo: [useremail@gmail.com] - Password_Odoo: [krlitos] - DB_Odoo: [prueba] 
2025-01-19 13:55:09,295 - 743pzpj7ltb65x2qt65y - {"host": "127.0.0.1", "request": "GET http://127.0.0.1:8000/api/v1/docs", "headers": {"host": "127.0.0.1:8000", "connection": "keep-alive", "cache-control": "max-age=0", "sec-ch-ua": "\"Google Chrome\";v=\"131\", \"Chromium\";v=\"131\", \"Not_A Brand\";v=\"24\"", "sec-ch-ua-mobile": "?0", "sec-ch-ua-platform": "\"Windows\"", "upgrade-insecure-requests": "1", "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36", "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7", "sec-fetch-site": "none", "sec-fetch-mode": "navigate", "sec-fetch-user": "?1", "sec-fetch-dest": "document", "accept-encoding": "gzip, deflate, br, zstd", "accept-language": "en-US,en;q=0.9,es;q=0.8", "cookie": "_ga=GA1.1.1550307865.1730360116; _ga_TRBNXHQ0ZF=GS1.1.1730386478.2.0.1730386478.0.0.0; csrftoken=9hytPsARZqAgOZ96HGjRVfdJf7jPHBx9"}, "body": "", "slug": "743pzpj7ltb65x2qt65y"}
2025-01-19 13:55:09,482 - 4mmlza2rkspudbhnfrlh - {"host": "127.0.0.1", "request": "GET http://127.0.0.1:8000/api/v1/openapi.json", "headers": {"host": "127.0.0.1:8000", "connection": "keep-alive", "sec-ch-ua-platform": "\"Windows\"", "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36", "accept": "application/json,*/*", "sec-ch-ua": "\"Google Chrome\";v=\"131\", \"Chromium\";v=\"131\", \"Not_A Brand\";v=\"24\"", "sec-ch-ua-mobile": "?0", "sec-fetch-site": "same-origin", "sec-fetch-mode": "cors", "sec-fetch-dest": "empty", "referer": "http://127.0.0.1:8000/api/v1/docs", "accept-encoding": "gzip, deflate, br, zstd", "accept-language": "en-US,en;q=0.9,es;q=0.8", "cookie": "_ga=GA1.1.1550307865.1730360116; _ga_TRBNXHQ0ZF=GS1.1.1730386478.2.0.1730386478.0.0.0; csrftoken=9hytPsARZqAgOZ96HGjRVfdJf7jPHBx9"}, "body": "", "slug": "4mmlza2rkspudbhnfrlh"}
2025-01-19 13:55:24,090 - y92hfunn494h0fbj79w6 - {"host": "127.0.0.1", "request": "GET http://127.0.0.1:8000/metrics", "headers": {"host": "127.0.0.1:8000", "connection": "keep-alive", "sec-ch-ua": "\"Google Chrome\";v=\"131\", \"Chromium\";v=\"131\", \"Not_A Brand\";v=\"24\"", "sec-ch-ua-mobile": "?0", "sec-ch-ua-platform": "\"Windows\"", "upgrade-insecure-requests": "1", "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36", "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7", "sec-fetch-site": "none", "sec-fetch-mode": "navigate", "sec-fetch-user": "?1", "sec-fetch-dest": "document", "accept-encoding": "gzip, deflate, br, zstd", "accept-language": "en-US,en;q=0.9,es;q=0.8", "cookie": "_ga=GA1.1.1550307865.1730360116; _ga_TRBNXHQ0ZF=GS1.1.1730386478.2.0.1730386478.0.0.0; csrftoken=9hytPsARZqAgOZ96HGjRVfdJf7jPHBx9"}, "body": "", "slug": "y92hfunn494h0fbj79w6"}
2025-01-19 13:55:54,499 - y92hfunn494h0fbj79w6 - Finalizando el Servicio
2025-01-19 13:58:10,875 - unknown_slug - Error al conectar a la base de datos [Prueba] , Host: [localhost], Port: [1433], Usuario: [sa], Password: [*****]. Error : [(pyodbc.OperationalError) ('08001', '[08001] [Microsoft][ODBC Driver 17 for SQL Server]TCP Provider: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión.\r\n (10061) (SQLDriverConnect); [08001] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0); [08001] [Microsoft][ODBC Driver 17 for SQL Server]Invalid connection string attribute (0); [08001] [Microsoft][ODBC Driver 17 for SQL Server]A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online. (10061)')
(Background on this error at: https://sqlalche.me/e/20/e3q8)]
2025-01-19 13:58:11,042 - unknown_slug - Se ha establecido la conexion con la base de datos local Postgres
2025-01-19 13:58:11,050 - unknown_slug - Modo Desarrollador activado [Para desabilitar el modo desarrollador cambie la variable 'DEBUG' en el archivo .env]
2025-01-19 13:58:11,054 - unknown_slug - Error de conexion con el sistema Odoo: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión
2025-01-19 13:58:11,056 - unknown_slug - Host_Odoo: [http://localhost:8069] - User_Odoo: [useremail@gmail.com] - Password_Odoo: [krlitos] - DB_Odoo: [prueba] 
2025-01-19 13:58:14,214 - 0qk3l1x2i7yha4v1sqv6 - {"host": "127.0.0.1", "request": "GET http://127.0.0.1:8000/metrics", "headers": {"host": "127.0.0.1:8000", "connection": "keep-alive", "cache-control": "max-age=0", "sec-ch-ua": "\"Google Chrome\";v=\"131\", \"Chromium\";v=\"131\", \"Not_A Brand\";v=\"24\"", "sec-ch-ua-mobile": "?0", "sec-ch-ua-platform": "\"Windows\"", "upgrade-insecure-requests": "1", "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36", "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7", "sec-fetch-site": "none", "sec-fetch-mode": "navigate", "sec-fetch-user": "?1", "sec-fetch-dest": "document", "accept-encoding": "gzip, deflate, br, zstd", "accept-language": "en-US,en;q=0.9,es;q=0.8", "cookie": "_ga=GA1.1.1550307865.1730360116; _ga_TRBNXHQ0ZF=GS1.1.1730386478.2.0.1730386478.0.0.0; csrftoken=9hytPsARZqAgOZ96HGjRVfdJf7jPHBx9"}, "body": "", "slug": "0qk3l1x2i7yha4v1sqv6"}
2025-01-19 13:58:23,535 - sima62hxeadwsckwjrpa - {"host": "127.0.0.1", "request": "GET http://127.0.0.1:8000/metrics", "headers": {"host": "127.0.0.1:8000", "connection": "keep-alive", "cache-control": "max-age=0", "sec-ch-ua": "\"Google Chrome\";v=\"131\", \"Chromium\";v=\"131\", \"Not_A Brand\";v=\"24\"", "sec-ch-ua-mobile": "?0", "sec-ch-ua-platform": "\"Windows\"", "upgrade-insecure-requests": "1", "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36", "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7", "sec-fetch-site": "none", "sec-fetch-mode": "navigate", "sec-fetch-user": "?1", "sec-fetch-dest": "document", "accept-encoding": "gzip, deflate, br, zstd", "accept-language": "en-US,en;q=0.9,es;q=0.8", "cookie": "_ga=GA1.1.1550307865.1730360116; _ga_TRBNXHQ0ZF=GS1.1.1730386478.2.0.1730386478.0.0.0; csrftoken=9hytPsARZqAgOZ96HGjRVfdJf7jPHBx9"}, "body": "", "slug": "sima62hxeadwsckwjrpa"}
2025-01-19 13:58:28,343 - ocb7lrr9kvjcdosyrxki - {"host": "127.0.0.1", "request": "GET http://127.0.0.1:8000/metrics", "headers": {"host": "127.0.0.1:8000", "connection": "keep-alive", "cache-control": "max-age=0", "sec-ch-ua": "\"Google Chrome\";v=\"131\", \"Chromium\";v=\"131\", \"Not_A Brand\";v=\"24\"", "sec-ch-ua-mobile": "?0", "sec-ch-ua-platform": "\"Windows\"", "upgrade-insecure-requests": "1", "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36", "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7", "sec-fetch-site": "none", "sec-fetch-mode": "navigate", "sec-fetch-user": "?1", "sec-fetch-dest": "document", "accept-encoding": "gzip, deflate, br, zstd", "accept-language": "en-US,en;q=0.9,es;q=0.8", "cookie": "_ga=GA1.1.1550307865.1730360116; _ga_TRBNXHQ0ZF=GS1.1.1730386478.2.0.1730386478.0.0.0; csrftoken=9hytPsARZqAgOZ96HGjRVfdJf7jPHBx9"}, "body": "", "slug": "ocb7lrr9kvjcdosyrxki"}
2025-01-19 13:58:31,633 - psehkj37ahuentngorck - {"host": "127.0.0.1", "request": "GET http://127.0.0.1:8000/metrics", "headers": {"host": "127.0.0.1:8000", "connection": "keep-alive", "cache-control": "max-age=0", "sec-ch-ua": "\"Google Chrome\";v=\"131\", \"Chromium\";v=\"131\", \"Not_A Brand\";v=\"24\"", "sec-ch-ua-mobile": "?0", "sec-ch-ua-platform": "\"Windows\"", "upgrade-insecure-requests": "1", "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36", "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7", "sec-fetch-site": "none", "sec-fetch-mode": "navigate", "sec-fetch-user": "?1", "sec-fetch-dest": "document", "accept-encoding": "gzip, deflate, br, zstd", "accept-language": "en-US,en;q=0.9,es;q=0.8", "cookie": "_ga=GA1.1.1550307865.1730360116; _ga_TRBNXHQ0ZF=GS1.1.1730386478.2.0.1730386478.0.0.0; csrftoken=9hytPsARZqAgOZ96HGjRVfdJf7jPHBx9"}, "body": "", "slug": "psehkj37ahuentngorck"}
2025-01-19 13:58:42,121 - psehkj37ahuentngorck - Finalizando el Servicio
2025-01-19 13:59:05,873 - unknown_slug - Error al conectar a la base de datos [Prueba] , Host: [localhost], Port: [1433], Usuario: [sa], Password: [*****]. Error : [(pyodbc.OperationalError) ('08001', '[08001] [Microsoft][ODBC Driver 17 for SQL Server]TCP Provider: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión.\r\n (10061) (SQLDriverConnect); [08001] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0); [08001] [Microsoft][ODBC Driver 17 for SQL Server]Invalid connection string attribute (0); [08001] [Microsoft][ODBC Driver 17 for SQL Server]A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online. (10061)')
(Background on this error at: https://sqlalche.me/e/20/e3q8)]
2025-01-19 13:59:05,993 - unknown_slug - Se ha establecido la conexion con la base de datos local Postgres
2025-01-19 13:59:06,015 - unknown_slug - Modo Desarrollador activado [Para desabilitar el modo desarrollador cambie la variable 'DEBUG' en el archivo .env]
2025-01-19 13:59:06,020 - unknown_slug - Error de conexion con el sistema Odoo: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión
2025-01-19 13:59:06,023 - unknown_slug - Host_Odoo: [http://localhost:8069] - User_Odoo: [useremail@gmail.com] - Password_Odoo: [krlitos] - DB_Odoo: [prueba] 
2025-01-19 13:59:08,369 - fbafry6k2vptv3qn8mu3 - {"host": "127.0.0.1", "request": "GET http://127.0.0.1:8000/metrics", "headers": {"host": "127.0.0.1:8000", "connection": "keep-alive", "cache-control": "max-age=0", "sec-ch-ua": "\"Google Chrome\";v=\"131\", \"Chromium\";v=\"131\", \"Not_A Brand\";v=\"24\"", "sec-ch-ua-mobile": "?0", "sec-ch-ua-platform": "\"Windows\"", "upgrade-insecure-requests": "1", "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36", "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7", "sec-fetch-site": "none", "sec-fetch-mode": "navigate", "sec-fetch-user": "?1", "sec-fetch-dest": "document", "accept-encoding": "gzip, deflate, br, zstd", "accept-language": "en-US,en;q=0.9,es;q=0.8", "cookie": "_ga=GA1.1.1550307865.1730360116; _ga_TRBNXHQ0ZF=GS1.1.1730386478.2.0.1730386478.0.0.0; csrftoken=9hytPsARZqAgOZ96HGjRVfdJf7jPHBx9"}, "body": "", "slug": "fbafry6k2vptv3qn8mu3"}
2025-01-19 13:59:12,398 - ia1xqb45icleqau0nhbj - {"host": "127.0.0.1", "request": "GET http://127.0.0.1:8000/api/v1/docs", "headers": {"host": "127.0.0.1:8000", "connection": "keep-alive", "cache-control": "max-age=0", "sec-ch-ua": "\"Google Chrome\";v=\"131\", \"Chromium\";v=\"131\", \"Not_A Brand\";v=\"24\"", "sec-ch-ua-mobile": "?0", "sec-ch-ua-platform": "\"Windows\"", "upgrade-insecure-requests": "1", "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36", "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7", "sec-fetch-site": "none", "sec-fetch-mode": "navigate", "sec-fetch-user": "?1", "sec-fetch-dest": "document", "accept-encoding": "gzip, deflate, br, zstd", "accept-language": "en-US,en;q=0.9,es;q=0.8", "cookie": "_ga=GA1.1.1550307865.1730360116; _ga_TRBNXHQ0ZF=GS1.1.1730386478.2.0.1730386478.0.0.0; csrftoken=9hytPsARZqAgOZ96HGjRVfdJf7jPHBx9"}, "body": "", "slug": "ia1xqb45icleqau0nhbj"}
2025-01-19 13:59:12,520 - 77imeh5ou16f9xvarohf - {"host": "127.0.0.1", "request": "GET http://127.0.0.1:8000/api/v1/openapi.json", "headers": {"host": "127.0.0.1:8000", "connection": "keep-alive", "sec-ch-ua-platform": "\"Windows\"", "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36", "accept": "application/json,*/*", "sec-ch-ua": "\"Google Chrome\";v=\"131\", \"Chromium\";v=\"131\", \"Not_A Brand\";v=\"24\"", "sec-ch-ua-mobile": "?0", "sec-fetch-site": "same-origin", "sec-fetch-mode": "cors", "sec-fetch-dest": "empty", "referer": "http://127.0.0.1:8000/api/v1/docs", "accept-encoding": "gzip, deflate, br, zstd", "accept-language": "en-US,en;q=0.9,es;q=0.8", "cookie": "_ga=GA1.1.1550307865.1730360116; _ga_TRBNXHQ0ZF=GS1.1.1730386478.2.0.1730386478.0.0.0; csrftoken=9hytPsARZqAgOZ96HGjRVfdJf7jPHBx9"}, "body": "", "slug": "77imeh5ou16f9xvarohf"}
2025-01-19 13:59:23,439 - 37o6c0gr97k214s4pj9m - {"host": "127.0.0.1", "request": "POST http://127.0.0.1:8000/api/v1/synclineal/", "headers": {"host": "127.0.0.1:8000", "connection": "keep-alive", "content-length": "68", "client_name_header": "SyncLineal", "sec-ch-ua-platform": "\"Windows\"", "sec-ch-ua": "\"Google Chrome\";v=\"131\", \"Chromium\";v=\"131\", \"Not_A Brand\";v=\"24\"", "sec-ch-ua-mobile": "?0", "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36", "accept": "application/json", "content-type": "application/json", "id_event_header": "TestSyncLineal", "origin": "http://127.0.0.1:8000", "sec-fetch-site": "same-origin", "sec-fetch-mode": "cors", "sec-fetch-dest": "empty", "referer": "http://127.0.0.1:8000/api/v1/docs", "accept-encoding": "gzip, deflate, br, zstd", "accept-language": "en-US,en;q=0.9,es;q=0.8", "cookie": "_ga=GA1.1.1550307865.1730360116; _ga_TRBNXHQ0ZF=GS1.1.1730386478.2.0.1730386478.0.0.0; csrftoken=9hytPsARZqAgOZ96HGjRVfdJf7jPHBx9"}, "body": "{\n  \"id\": 0,\n  \"tipo_persona_id\": [\n    1,\n    2,\n    3,\n    4\n  ]\n}", "slug": "37o6c0gr97k214s4pj9m"}
2025-01-19 13:59:23,439 - unknown_slug - Buscando datos del cliente con ID [0] en la Base de datos de Odoo, en la tabla ['res.partner']
2025-01-19 13:59:23,439 - unknown_slug - Buscando datos del cliente con ID [0] en la Base de datos de Odoo, en la tabla ['res.partner']
2025-01-19 13:59:23,439 - unknown_slug - Buscando datos del cliente con ID [0] en la Base de datos de Odoo, en la tabla ['res.partner']
2025-01-19 13:59:27,550 - unknown_slug - No se encontro ningun cliente con el id [0] en la tabla [res.partner]. Es probable que este cliente no se encuentre en la base de datos o se encuentre con el campo [active=false]. Error: [cannot marshal None unless allow_none is enabled]
2025-01-19 13:59:27,550 - unknown_slug - No se encontro ningun cliente con el id [0] en la tabla [res.partner]. Es probable que este cliente no se encuentre en la base de datos o se encuentre con el campo [active=false]. Error: [cannot marshal None unless allow_none is enabled]
2025-01-19 13:59:27,550 - unknown_slug - No se encontro ningun cliente con el id [0] en la tabla [res.partner]. Es probable que este cliente no se encuentre en la base de datos o se encuentre con el campo [active=false]. Error: [cannot marshal None unless allow_none is enabled]
2025-01-19 14:00:14,048 - zr6pupool1ern3o2ctxu - {"host": "127.0.0.1", "request": "POST http://127.0.0.1:8000/api/v1/synclineal/", "headers": {"host": "127.0.0.1:8000", "connection": "keep-alive", "content-length": "68", "client_name_header": "SyncLineal", "sec-ch-ua-platform": "\"Windows\"", "sec-ch-ua": "\"Google Chrome\";v=\"131\", \"Chromium\";v=\"131\", \"Not_A Brand\";v=\"24\"", "sec-ch-ua-mobile": "?0", "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36", "accept": "application/json", "content-type": "application/json", "id_event_header": "TestSyncLineal", "origin": "http://127.0.0.1:8000", "sec-fetch-site": "same-origin", "sec-fetch-mode": "cors", "sec-fetch-dest": "empty", "referer": "http://127.0.0.1:8000/api/v1/docs", "accept-encoding": "gzip, deflate, br, zstd", "accept-language": "en-US,en;q=0.9,es;q=0.8", "cookie": "_ga=GA1.1.1550307865.1730360116; _ga_TRBNXHQ0ZF=GS1.1.1730386478.2.0.1730386478.0.0.0; csrftoken=9hytPsARZqAgOZ96HGjRVfdJf7jPHBx9"}, "body": "{\n  \"id\": 0,\n  \"tipo_persona_id\": [\n    1,\n    2,\n    3,\n    4\n  ]\n}", "slug": "zr6pupool1ern3o2ctxu"}
2025-01-19 14:00:14,065 - unknown_slug - Buscando datos del cliente con ID [0] en la Base de datos de Odoo, en la tabla ['res.partner']
2025-01-19 14:00:14,065 - unknown_slug - Buscando datos del cliente con ID [0] en la Base de datos de Odoo, en la tabla ['res.partner']
2025-01-19 14:00:14,065 - unknown_slug - Buscando datos del cliente con ID [0] en la Base de datos de Odoo, en la tabla ['res.partner']
2025-01-19 14:00:18,105 - unknown_slug - No se encontro ningun cliente con el id [0] en la tabla [res.partner]. Es probable que este cliente no se encuentre en la base de datos o se encuentre con el campo [active=false]. Error: [cannot marshal None unless allow_none is enabled]
2025-01-19 14:00:18,105 - unknown_slug - No se encontro ningun cliente con el id [0] en la tabla [res.partner]. Es probable que este cliente no se encuentre en la base de datos o se encuentre con el campo [active=false]. Error: [cannot marshal None unless allow_none is enabled]
2025-01-19 14:00:18,120 - unknown_slug - No se encontro ningun cliente con el id [0] en la tabla [res.partner]. Es probable que este cliente no se encuentre en la base de datos o se encuentre con el campo [active=false]. Error: [cannot marshal None unless allow_none is enabled]
2025-01-19 14:00:36,987 - zr6pupool1ern3o2ctxu - Finalizando el Servicio
2025-01-19 14:01:22,526 - unknown_slug - Error al conectar a la base de datos [Prueba] , Host: [localhost], Port: [1433], Usuario: [sa], Password: [*****]. Error : [(pyodbc.OperationalError) ('08001', '[08001] [Microsoft][ODBC Driver 17 for SQL Server]TCP Provider: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión.\r\n (10061) (SQLDriverConnect); [08001] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0); [08001] [Microsoft][ODBC Driver 17 for SQL Server]Invalid connection string attribute (0); [08001] [Microsoft][ODBC Driver 17 for SQL Server]A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online. (10061)')
(Background on this error at: https://sqlalche.me/e/20/e3q8)]
2025-01-19 14:01:22,657 - unknown_slug - Se ha establecido la conexion con la base de datos local Postgres
2025-01-19 14:01:22,668 - unknown_slug - Modo Desarrollador activado [Para desabilitar el modo desarrollador cambie la variable 'DEBUG' en el archivo .env]
2025-01-19 14:01:22,673 - unknown_slug - Error de conexion con el sistema Odoo: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión
2025-01-19 14:01:22,676 - unknown_slug - Host_Odoo: [http://localhost:8069] - User_Odoo: [useremail@gmail.com] - Password_Odoo: [krlitos] - DB_Odoo: [prueba] 
2025-01-19 14:01:25,479 - fi1tc3b2zjz557rfc0n1 - {"host": "127.0.0.1", "request": "POST http://127.0.0.1:8000/api/v1/synclineal/", "headers": {"host": "127.0.0.1:8000", "connection": "keep-alive", "content-length": "68", "client_name_header": "SyncLineal", "sec-ch-ua-platform": "\"Windows\"", "sec-ch-ua": "\"Google Chrome\";v=\"131\", \"Chromium\";v=\"131\", \"Not_A Brand\";v=\"24\"", "sec-ch-ua-mobile": "?0", "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36", "accept": "application/json", "content-type": "application/json", "id_event_header": "TestSyncLineal", "origin": "http://127.0.0.1:8000", "sec-fetch-site": "same-origin", "sec-fetch-mode": "cors", "sec-fetch-dest": "empty", "referer": "http://127.0.0.1:8000/api/v1/docs", "accept-encoding": "gzip, deflate, br, zstd", "accept-language": "en-US,en;q=0.9,es;q=0.8", "cookie": "_ga=GA1.1.1550307865.1730360116; _ga_TRBNXHQ0ZF=GS1.1.1730386478.2.0.1730386478.0.0.0; csrftoken=9hytPsARZqAgOZ96HGjRVfdJf7jPHBx9"}, "body": "{\n  \"id\": 0,\n  \"tipo_persona_id\": [\n    1,\n    2,\n    3,\n    4\n  ]\n}", "slug": "fi1tc3b2zjz557rfc0n1"}
2025-01-19 14:01:25,485 - unknown_slug - Buscando datos del cliente con ID [0] en la Base de datos de Odoo, en la tabla ['res.partner']
2025-01-19 14:01:25,485 - unknown_slug - Buscando datos del cliente con ID [0] en la Base de datos de Odoo, en la tabla ['res.partner']
2025-01-19 14:01:29,543 - unknown_slug - No se encontro ningun cliente con el id [0] en la tabla [res.partner]. Es probable que este cliente no se encuentre en la base de datos o se encuentre con el campo [active=false]. Error: [cannot marshal None unless allow_none is enabled]
2025-01-19 14:01:29,543 - unknown_slug - No se encontro ningun cliente con el id [0] en la tabla [res.partner]. Es probable que este cliente no se encuentre en la base de datos o se encuentre con el campo [active=false]. Error: [cannot marshal None unless allow_none is enabled]
2025-01-19 14:01:39,554 - unknown_slug - Buscando datos del cliente con ID [0] en la Base de datos de Odoo, en la tabla ['res.partner']
2025-01-19 14:01:43,611 - unknown_slug - No se encontro ningun cliente con el id [0] en la tabla [res.partner]. Es probable que este cliente no se encuentre en la base de datos o se encuentre con el campo [active=false]. Error: [cannot marshal None unless allow_none is enabled]
2025-01-19 14:02:26,995 - fi1tc3b2zjz557rfc0n1 - Finalizando el Servicio
2025-01-19 14:03:39,627 - unknown_slug - Error al conectar a la base de datos [Prueba] , Host: [localhost], Port: [1433], Usuario: [sa], Password: [*****]. Error : [(pyodbc.OperationalError) ('08001', '[08001] [Microsoft][ODBC Driver 17 for SQL Server]TCP Provider: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión.\r\n (10061) (SQLDriverConnect); [08001] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0); [08001] [Microsoft][ODBC Driver 17 for SQL Server]Invalid connection string attribute (0); [08001] [Microsoft][ODBC Driver 17 for SQL Server]A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online. (10061)')
(Background on this error at: https://sqlalche.me/e/20/e3q8)]
2025-01-19 14:03:39,761 - unknown_slug - Se ha establecido la conexion con la base de datos local Postgres
2025-01-19 14:03:39,769 - unknown_slug - Modo Desarrollador activado [Para desabilitar el modo desarrollador cambie la variable 'DEBUG' en el archivo .env]
2025-01-19 14:03:39,775 - unknown_slug - Error de conexion con el sistema Odoo: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión
2025-01-19 14:03:39,779 - unknown_slug - Host_Odoo: [http://localhost:8069] - User_Odoo: [useremail@gmail.com] - Password_Odoo: [krlitos] - DB_Odoo: [prueba] 
2025-01-19 14:03:42,748 - 4o066osyer94w77rmanx - {"host": "127.0.0.1", "request": "POST http://127.0.0.1:8000/api/v1/synclineal/", "headers": {"host": "127.0.0.1:8000", "connection": "keep-alive", "content-length": "68", "client_name_header": "SyncLineal", "sec-ch-ua-platform": "\"Windows\"", "sec-ch-ua": "\"Google Chrome\";v=\"131\", \"Chromium\";v=\"131\", \"Not_A Brand\";v=\"24\"", "sec-ch-ua-mobile": "?0", "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36", "accept": "application/json", "content-type": "application/json", "id_event_header": "TestSyncLineal", "origin": "http://127.0.0.1:8000", "sec-fetch-site": "same-origin", "sec-fetch-mode": "cors", "sec-fetch-dest": "empty", "referer": "http://127.0.0.1:8000/api/v1/docs", "accept-encoding": "gzip, deflate, br, zstd", "accept-language": "en-US,en;q=0.9,es;q=0.8", "cookie": "_ga=GA1.1.1550307865.1730360116; _ga_TRBNXHQ0ZF=GS1.1.1730386478.2.0.1730386478.0.0.0; csrftoken=9hytPsARZqAgOZ96HGjRVfdJf7jPHBx9"}, "body": "{\n  \"id\": 0,\n  \"tipo_persona_id\": [\n    1,\n    2,\n    3,\n    4\n  ]\n}", "slug": "4o066osyer94w77rmanx"}
2025-01-19 14:03:42,750 - 4o066osyer94w77rmanx - Buscando datos del cliente con ID [0] en la Base de datos de Odoo, en la tabla ['res.partner']
2025-01-19 14:03:46,788 - 4o066osyer94w77rmanx - No se encontro ningun cliente con el id [0] en la tabla [res.partner]. Es probable que este cliente no se encuentre en la base de datos o se encuentre con el campo [active=false]. Error: [cannot marshal None unless allow_none is enabled]
2025-01-19 14:03:56,797 - 4o066osyer94w77rmanx - Buscando datos del cliente con ID [0] en la Base de datos de Odoo, en la tabla ['res.partner']
2025-01-19 14:04:00,840 - 4o066osyer94w77rmanx - No se encontro ningun cliente con el id [0] en la tabla [res.partner]. Es probable que este cliente no se encuentre en la base de datos o se encuentre con el campo [active=false]. Error: [cannot marshal None unless allow_none is enabled]
2025-01-19 14:04:10,848 - 4o066osyer94w77rmanx - Buscando datos del cliente con ID [0] en la Base de datos de Odoo, en la tabla ['res.partner']
2025-01-19 14:04:14,888 - 4o066osyer94w77rmanx - No se encontro ningun cliente con el id [0] en la tabla [res.partner]. Es probable que este cliente no se encuentre en la base de datos o se encuentre con el campo [active=false]. Error: [cannot marshal None unless allow_none is enabled]
2025-01-19 14:05:35,161 - 4o066osyer94w77rmanx - Finalizando el Servicio
2025-01-19 14:06:02,580 - unknown_slug - Error al conectar a la base de datos [Prueba] , Host: [localhost], Port: [1433], Usuario: [sa], Password: [*****]. Error : [(pyodbc.OperationalError) ('08001', '[08001] [Microsoft][ODBC Driver 17 for SQL Server]TCP Provider: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión.\r\n (10061) (SQLDriverConnect); [08001] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0); [08001] [Microsoft][ODBC Driver 17 for SQL Server]Invalid connection string attribute (0); [08001] [Microsoft][ODBC Driver 17 for SQL Server]A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online. (10061)')
(Background on this error at: https://sqlalche.me/e/20/e3q8)]
2025-01-19 14:06:02,698 - unknown_slug - Se ha establecido la conexion con la base de datos local Postgres
2025-01-19 14:06:02,722 - unknown_slug - Modo Desarrollador activado [Para desabilitar el modo desarrollador cambie la variable 'DEBUG' en el archivo .env]
2025-01-19 14:06:02,726 - unknown_slug - Error de conexion con el sistema Odoo: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión
2025-01-19 14:06:02,729 - unknown_slug - Host_Odoo: [http://localhost:8069] - User_Odoo: [useremail@gmail.com] - Password_Odoo: [krlitos] - DB_Odoo: [prueba] 
2025-01-19 14:06:09,476 - pulhoo3mkrhrc265sxm5 - {"host": "127.0.0.1", "request": "POST http://127.0.0.1:8000/api/v1/synclineal/", "headers": {"host": "127.0.0.1:8000", "connection": "keep-alive", "content-length": "68", "client_name_header": "SyncLineal", "sec-ch-ua-platform": "\"Windows\"", "sec-ch-ua": "\"Google Chrome\";v=\"131\", \"Chromium\";v=\"131\", \"Not_A Brand\";v=\"24\"", "sec-ch-ua-mobile": "?0", "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36", "accept": "application/json", "content-type": "application/json", "id_event_header": "TestSyncLineal", "origin": "http://127.0.0.1:8000", "sec-fetch-site": "same-origin", "sec-fetch-mode": "cors", "sec-fetch-dest": "empty", "referer": "http://127.0.0.1:8000/api/v1/docs", "accept-encoding": "gzip, deflate, br, zstd", "accept-language": "en-US,en;q=0.9,es;q=0.8", "cookie": "_ga=GA1.1.1550307865.1730360116; _ga_TRBNXHQ0ZF=GS1.1.1730386478.2.0.1730386478.0.0.0; csrftoken=9hytPsARZqAgOZ96HGjRVfdJf7jPHBx9"}, "body": "{\n  \"id\": 0,\n  \"tipo_persona_id\": [\n    1,\n    2,\n    3,\n    4\n  ]\n}", "slug": "pulhoo3mkrhrc265sxm5"}
2025-01-19 14:06:09,476 - pulhoo3mkrhrc265sxm5 - Buscando datos del cliente con ID [0] en la Base de datos de Odoo, en la tabla ['res.partner']
2025-01-19 14:06:13,550 - pulhoo3mkrhrc265sxm5 - No se encontro ningun cliente con el id [0] en la tabla [res.partner]. Es probable que este cliente no se encuentre en la base de datos o se encuentre con el campo [active=false]. Error: [cannot marshal None unless allow_none is enabled]
2025-01-19 14:06:23,556 - pulhoo3mkrhrc265sxm5 - Buscando datos del cliente con ID [0] en la Base de datos de Odoo, en la tabla ['res.partner']
2025-01-19 14:06:27,619 - pulhoo3mkrhrc265sxm5 - No se encontro ningun cliente con el id [0] en la tabla [res.partner]. Es probable que este cliente no se encuentre en la base de datos o se encuentre con el campo [active=false]. Error: [cannot marshal None unless allow_none is enabled]
2025-01-19 14:06:37,626 - pulhoo3mkrhrc265sxm5 - Buscando datos del cliente con ID [0] en la Base de datos de Odoo, en la tabla ['res.partner']
2025-01-19 14:06:41,683 - pulhoo3mkrhrc265sxm5 - No se encontro ningun cliente con el id [0] en la tabla [res.partner]. Es probable que este cliente no se encuentre en la base de datos o se encuentre con el campo [active=false]. Error: [cannot marshal None unless allow_none is enabled]
2025-01-19 14:07:25,134 - pulhoo3mkrhrc265sxm5 - Finalizando el Servicio
2025-01-19 14:08:00,937 - unknown_slug - Error al conectar a la base de datos [Prueba] , Host: [localhost], Port: [1433], Usuario: [sa], Password: [*****]. Error : [(pyodbc.OperationalError) ('08001', '[08001] [Microsoft][ODBC Driver 17 for SQL Server]TCP Provider: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión.\r\n (10061) (SQLDriverConnect); [08001] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0); [08001] [Microsoft][ODBC Driver 17 for SQL Server]Invalid connection string attribute (0); [08001] [Microsoft][ODBC Driver 17 for SQL Server]A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online. (10061)')
(Background on this error at: https://sqlalche.me/e/20/e3q8)]
2025-01-19 14:08:01,062 - unknown_slug - Se ha establecido la conexion con la base de datos local Postgres
2025-01-19 14:08:01,071 - unknown_slug - Modo Desarrollador activado [Para desabilitar el modo desarrollador cambie la variable 'DEBUG' en el archivo .env]
2025-01-19 14:08:01,075 - unknown_slug - Error de conexion con el sistema Odoo: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión
2025-01-19 14:08:01,078 - unknown_slug - Host_Odoo: [http://localhost:8069] - User_Odoo: [useremail@gmail.com] - Password_Odoo: [krlitos] - DB_Odoo: [prueba] 
2025-01-19 14:08:14,246 - rzvb90njpjlc7p8ppn42 - {"host": "127.0.0.1", "request": "POST http://127.0.0.1:8000/api/v1/synclineal/", "headers": {"host": "127.0.0.1:8000", "connection": "keep-alive", "content-length": "68", "client_name_header": "SyncLineal", "sec-ch-ua-platform": "\"Windows\"", "sec-ch-ua": "\"Google Chrome\";v=\"131\", \"Chromium\";v=\"131\", \"Not_A Brand\";v=\"24\"", "sec-ch-ua-mobile": "?0", "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36", "accept": "application/json", "content-type": "application/json", "id_event_header": "TestSyncLineal", "origin": "http://127.0.0.1:8000", "sec-fetch-site": "same-origin", "sec-fetch-mode": "cors", "sec-fetch-dest": "empty", "referer": "http://127.0.0.1:8000/api/v1/docs", "accept-encoding": "gzip, deflate, br, zstd", "accept-language": "en-US,en;q=0.9,es;q=0.8", "cookie": "_ga=GA1.1.1550307865.1730360116; _ga_TRBNXHQ0ZF=GS1.1.1730386478.2.0.1730386478.0.0.0; csrftoken=9hytPsARZqAgOZ96HGjRVfdJf7jPHBx9"}, "body": "{\n  \"id\": 0,\n  \"tipo_persona_id\": [\n    1,\n    2,\n    3,\n    4\n  ]\n}", "slug": "rzvb90njpjlc7p8ppn42"}
2025-01-19 14:08:14,250 - unknown_slug - Buscando datos del cliente con ID [0] en la Base de datos de Odoo, en la tabla ['res.partner']
2025-01-19 14:08:14,250 - unknown_slug - Buscando datos del cliente con ID [0] en la Base de datos de Odoo, en la tabla ['res.partner']
2025-01-19 14:08:14,250 - unknown_slug - Buscando datos del cliente con ID [0] en la Base de datos de Odoo, en la tabla ['res.partner']
2025-01-19 14:08:18,281 - unknown_slug - No se encontro ningun cliente con el id [0] en la tabla [res.partner]. Es probable que este cliente no se encuentre en la base de datos o se encuentre con el campo [active=false]. Error: [cannot marshal None unless allow_none is enabled]
2025-01-19 14:08:18,296 - unknown_slug - No se encontro ningun cliente con el id [0] en la tabla [res.partner]. Es probable que este cliente no se encuentre en la base de datos o se encuentre con el campo [active=false]. Error: [cannot marshal None unless allow_none is enabled]
2025-01-19 14:08:18,296 - unknown_slug - No se encontro ningun cliente con el id [0] en la tabla [res.partner]. Es probable que este cliente no se encuentre en la base de datos o se encuentre con el campo [active=false]. Error: [cannot marshal None unless allow_none is enabled]
2025-01-19 14:08:34,024 - rzvb90njpjlc7p8ppn42 - Finalizando el Servicio
2025-01-19 14:14:33,861 - unknown_slug - Error al conectar a la base de datos [Prueba] , Host: [localhost], Port: [1433], Usuario: [sa], Password: [*****]. Error : [(pyodbc.OperationalError) ('08001', '[08001] [Microsoft][ODBC Driver 17 for SQL Server]TCP Provider: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión.\r\n (10061) (SQLDriverConnect); [08001] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0); [08001] [Microsoft][ODBC Driver 17 for SQL Server]Invalid connection string attribute (0); [08001] [Microsoft][ODBC Driver 17 for SQL Server]A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online. (10061)')
(Background on this error at: https://sqlalche.me/e/20/e3q8)]
2025-01-19 14:14:34,040 - unknown_slug - Se ha establecido la conexion con la base de datos local Postgres
2025-01-19 14:14:34,054 - unknown_slug - Modo Desarrollador activado [Para desabilitar el modo desarrollador cambie la variable 'DEBUG' en el archivo .env]
2025-01-19 14:14:34,060 - unknown_slug - Error de conexion con el sistema Odoo: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión
2025-01-19 14:14:34,066 - unknown_slug - Host_Odoo: [http://localhost:8069] - User_Odoo: [useremail@gmail.com] - Password_Odoo: [krlitos] - DB_Odoo: [prueba] 
2025-01-19 14:14:58,502 - f7o8aq7yiatlh5ygx8cq - {"host": "127.0.0.1", "request": "GET http://127.0.0.1:8000/api/v1/docs", "headers": {"host": "127.0.0.1:8000", "connection": "keep-alive", "cache-control": "max-age=0", "sec-ch-ua": "\"Google Chrome\";v=\"131\", \"Chromium\";v=\"131\", \"Not_A Brand\";v=\"24\"", "sec-ch-ua-mobile": "?0", "sec-ch-ua-platform": "\"Windows\"", "upgrade-insecure-requests": "1", "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36", "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7", "sec-fetch-site": "none", "sec-fetch-mode": "navigate", "sec-fetch-user": "?1", "sec-fetch-dest": "document", "accept-encoding": "gzip, deflate, br, zstd", "accept-language": "en-US,en;q=0.9,es;q=0.8", "cookie": "_ga=GA1.1.1550307865.1730360116; _ga_TRBNXHQ0ZF=GS1.1.1730386478.2.0.1730386478.0.0.0; csrftoken=9hytPsARZqAgOZ96HGjRVfdJf7jPHBx9"}, "body": "", "slug": "f7o8aq7yiatlh5ygx8cq"}
2025-01-19 14:14:58,672 - 5av2b5w62afip49qqgih - {"host": "127.0.0.1", "request": "GET http://127.0.0.1:8000/api/v1/openapi.json", "headers": {"host": "127.0.0.1:8000", "connection": "keep-alive", "sec-ch-ua-platform": "\"Windows\"", "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36", "accept": "application/json,*/*", "sec-ch-ua": "\"Google Chrome\";v=\"131\", \"Chromium\";v=\"131\", \"Not_A Brand\";v=\"24\"", "sec-ch-ua-mobile": "?0", "sec-fetch-site": "same-origin", "sec-fetch-mode": "cors", "sec-fetch-dest": "empty", "referer": "http://127.0.0.1:8000/api/v1/docs", "accept-encoding": "gzip, deflate, br, zstd", "accept-language": "en-US,en;q=0.9,es;q=0.8", "cookie": "_ga=GA1.1.1550307865.1730360116; _ga_TRBNXHQ0ZF=GS1.1.1730386478.2.0.1730386478.0.0.0; csrftoken=9hytPsARZqAgOZ96HGjRVfdJf7jPHBx9"}, "body": "", "slug": "5av2b5w62afip49qqgih"}
2025-01-19 14:15:06,757 - rno2ex9r6951qe57qyn0 - {"host": "127.0.0.1", "request": "GET http://127.0.0.1:8000/logs_with_alerts", "headers": {"host": "127.0.0.1:8000", "connection": "keep-alive", "sec-ch-ua-platform": "\"Windows\"", "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36", "accept": "application/json", "sec-ch-ua": "\"Google Chrome\";v=\"131\", \"Chromium\";v=\"131\", \"Not_A Brand\";v=\"24\"", "sec-ch-ua-mobile": "?0", "sec-fetch-site": "same-origin", "sec-fetch-mode": "cors", "sec-fetch-dest": "empty", "referer": "http://127.0.0.1:8000/api/v1/docs", "accept-encoding": "gzip, deflate, br, zstd", "accept-language": "en-US,en;q=0.9,es;q=0.8", "cookie": "_ga=GA1.1.1550307865.1730360116; _ga_TRBNXHQ0ZF=GS1.1.1730386478.2.0.1730386478.0.0.0; csrftoken=9hytPsARZqAgOZ96HGjRVfdJf7jPHBx9"}, "body": "", "slug": "rno2ex9r6951qe57qyn0"}
2025-01-19 14:15:25,800 - 06zesglbwomjqmj69536 - {"host": "127.0.0.1", "request": "GET http://127.0.0.1:8000/logs_with_alerts", "headers": {"host": "127.0.0.1:8000", "connection": "keep-alive", "authorization": "Basic YWRtaW46c2VjcmV0", "sec-ch-ua-platform": "\"Windows\"", "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36", "accept": "application/json", "sec-ch-ua": "\"Google Chrome\";v=\"131\", \"Chromium\";v=\"131\", \"Not_A Brand\";v=\"24\"", "sec-ch-ua-mobile": "?0", "sec-fetch-site": "same-origin", "sec-fetch-mode": "cors", "sec-fetch-dest": "empty", "referer": "http://127.0.0.1:8000/api/v1/docs", "accept-encoding": "gzip, deflate, br, zstd", "accept-language": "en-US,en;q=0.9,es;q=0.8", "cookie": "_ga=GA1.1.1550307865.1730360116; _ga_TRBNXHQ0ZF=GS1.1.1730386478.2.0.1730386478.0.0.0; csrftoken=9hytPsARZqAgOZ96HGjRVfdJf7jPHBx9"}, "body": "", "slug": "06zesglbwomjqmj69536"}
2025-01-19 14:15:42,948 - wjiarz5ektxwlo4mpwb0 - {"host": "127.0.0.1", "request": "GET http://127.0.0.1:8000/logs_with_alerts", "headers": {"host": "127.0.0.1:8000", "connection": "keep-alive", "authorization": "Basic YWRtaW46c2VjcmV0", "sec-ch-ua-platform": "\"Windows\"", "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36", "accept": "application/json", "sec-ch-ua": "\"Google Chrome\";v=\"131\", \"Chromium\";v=\"131\", \"Not_A Brand\";v=\"24\"", "sec-ch-ua-mobile": "?0", "sec-fetch-site": "same-origin", "sec-fetch-mode": "cors", "sec-fetch-dest": "empty", "referer": "http://127.0.0.1:8000/api/v1/docs", "accept-encoding": "gzip, deflate, br, zstd", "accept-language": "en-US,en;q=0.9,es;q=0.8", "cookie": "_ga=GA1.1.1550307865.1730360116; _ga_TRBNXHQ0ZF=GS1.1.1730386478.2.0.1730386478.0.0.0; csrftoken=9hytPsARZqAgOZ96HGjRVfdJf7jPHBx9"}, "body": "", "slug": "wjiarz5ektxwlo4mpwb0"}
2025-01-19 14:21:59,440 - jvqsl79tsl2tmggqw0cs - {"host": "127.0.0.1", "request": "POST http://127.0.0.1:8000/api/v1/synclineal/", "headers": {"host": "127.0.0.1:8000", "connection": "keep-alive", "content-length": "68", "authorization": "Basic YWRtaW46c2VjcmV0", "client_name_header": "SyncLineal", "sec-ch-ua-platform": "\"Windows\"", "sec-ch-ua": "\"Google Chrome\";v=\"131\", \"Chromium\";v=\"131\", \"Not_A Brand\";v=\"24\"", "sec-ch-ua-mobile": "?0", "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36", "accept": "application/json", "content-type": "application/json", "id_event_header": "TestSyncLineal", "origin": "http://127.0.0.1:8000", "sec-fetch-site": "same-origin", "sec-fetch-mode": "cors", "sec-fetch-dest": "empty", "referer": "http://127.0.0.1:8000/api/v1/docs", "accept-encoding": "gzip, deflate, br, zstd", "accept-language": "en-US,en;q=0.9,es;q=0.8", "cookie": "_ga=GA1.1.1550307865.1730360116; _ga_TRBNXHQ0ZF=GS1.1.1730386478.2.0.1730386478.0.0.0; csrftoken=9hytPsARZqAgOZ96HGjRVfdJf7jPHBx9"}, "body": "{\n  \"id\": 0,\n  \"tipo_persona_id\": [\n    1,\n    2,\n    3,\n    4\n  ]\n}", "slug": "jvqsl79tsl2tmggqw0cs"}
2025-01-19 14:21:59,455 - unknown_slug - Buscando datos del cliente con ID [0] en la Base de datos de Odoo, en la tabla ['res.partner']
2025-01-19 14:21:59,469 - unknown_slug - Buscando datos del cliente con ID [0] en la Base de datos de Odoo, en la tabla ['res.partner']
2025-01-19 14:21:59,469 - unknown_slug - Buscando datos del cliente con ID [0] en la Base de datos de Odoo, en la tabla ['res.partner']
2025-01-19 14:22:03,508 - unknown_slug - No se encontro ningun cliente con el id [0] en la tabla [res.partner]. Es probable que este cliente no se encuentre en la base de datos o se encuentre con el campo [active=false]. Error: [cannot marshal None unless allow_none is enabled]
2025-01-19 14:22:03,508 - unknown_slug - No se encontro ningun cliente con el id [0] en la tabla [res.partner]. Es probable que este cliente no se encuentre en la base de datos o se encuentre con el campo [active=false]. Error: [cannot marshal None unless allow_none is enabled]
2025-01-19 14:22:03,523 - unknown_slug - No se encontro ningun cliente con el id [0] en la tabla [res.partner]. Es probable que este cliente no se encuentre en la base de datos o se encuentre con el campo [active=false]. Error: [cannot marshal None unless allow_none is enabled]
2025-01-19 14:22:18,681 - jvqsl79tsl2tmggqw0cs - Finalizando el Servicio
